"""Add Excel import support

Revision ID: 000aee16baa1
Revises: 36746f735403
Create Date: 2026-05-23 23:50:28.130879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000aee16baa1'
down_revision = '36746f735403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('dry_run_summary_json', sa.Text(), nullable=True),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_sheet', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('import_batch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_row_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_device_source_sheet'), ['source_sheet'], unique=False)
        batch_op.create_foreign_key('fk_device_import_batch_id_import_batch', 'import_batch', ['import_batch_id'], ['id'])

    with op.batch_alter_table('unassigned_invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_sheet', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('import_batch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_row_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_unassigned_invoice_item_import_batch_id_import_batch', 'import_batch', ['import_batch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unassigned_invoice_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_unassigned_invoice_item_import_batch_id_import_batch', type_='foreignkey')
        batch_op.drop_column('imported_at')
        batch_op.drop_column('source_row_number')
        batch_op.drop_column('import_batch_id')
        batch_op.drop_column('source_sheet')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint('fk_device_import_batch_id_import_batch', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_device_source_sheet'))
        batch_op.drop_column('imported_at')
        batch_op.drop_column('source_row_number')
        batch_op.drop_column('import_batch_id')
        batch_op.drop_column('source_sheet')

    op.drop_table('import_batch')
    # ### end Alembic commands ###
