"""Add procurement and invoice fields

Revision ID: 36746f735403
Revises: 1676b753e9e0
Create Date: 2026-05-23 23:38:32.974703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36746f735403'
down_revision = '1676b753e9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unassigned_invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=120), nullable=True),
    sa.Column('partner', sa.String(length=160), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('accounting_fulfillment_date', sa.Date(), nullable=True),
    sa.Column('payment_deadline', sa.Date(), nullable=True),
    sa.Column('gross_amount_huf', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=12), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price_huf', sa.Float(), nullable=True),
    sa.Column('net_amount_huf', sa.Float(), nullable=True),
    sa.Column('vat_amount_huf', sa.Float(), nullable=True),
    sa.Column('line_gross_amount_huf', sa.Float(), nullable=True),
    sa.Column('assignment_status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_project_id', sa.Integer(), nullable=True),
    sa.Column('assigned_device_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['assigned_project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unassigned_invoice_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unassigned_invoice_item_assignment_status'), ['assignment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_unassigned_invoice_item_invoice_number'), ['invoice_number'], unique=False)

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('subtype_note', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('supplier_manufacturer', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit_net_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('huf_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('assignment_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('assignment_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('order_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_ordered', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('planned_arrival_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('actual_arrival_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('has_arrived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shipping_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('supplier_invoice_number', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('supplier_invoice_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('invoice_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shipping_invoice_number', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('shipping_invoice_paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('shipping_invoice_paid')
        batch_op.drop_column('shipping_invoice_number')
        batch_op.drop_column('invoice_value')
        batch_op.drop_column('supplier_invoice_paid')
        batch_op.drop_column('supplier_invoice_number')
        batch_op.drop_column('shipping_date')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('has_arrived')
        batch_op.drop_column('actual_arrival_date')
        batch_op.drop_column('planned_arrival_date')
        batch_op.drop_column('is_ordered')
        batch_op.drop_column('order_date')
        batch_op.drop_column('assignment_notes')
        batch_op.drop_column('assignment_quantity')
        batch_op.drop_column('huf_value')
        batch_op.drop_column('currency')
        batch_op.drop_column('unit_net_price')
        batch_op.drop_column('quantity')
        batch_op.drop_column('version')
        batch_op.drop_column('supplier_manufacturer')
        batch_op.drop_column('subtype_note')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('unassigned_invoice_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unassigned_invoice_item_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_unassigned_invoice_item_assignment_status'))

    op.drop_table('unassigned_invoice_item')
    # ### end Alembic commands ###
