"""Add archive fields for usability actions

Revision ID: 94b1120f7cfb
Revises: 000aee16baa1
Create Date: 2026-05-24 00:13:15.946011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b1120f7cfb'
down_revision = '000aee16baa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('unassigned_invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unassigned_invoice_item', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
